apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: prices
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
