apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: 02_Deploy/08_argo_rollout/app/shop-blue-green/base
    repoURL: "https://github.com/CCChou/OpenShift-PoC-Scenario.git"
    targetRevision: rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
