apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoweb
spec:
  destination:
    name: ""
    namespace: helm-demo
    server: "https://kubernetes.default.svc"
  source:
    path: 02_Deploy/03_helm_gitops_deploy/helm/myapp
    repoURL: "https://github.com/CCChou/OpenShift-PoC-Scenario.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
