apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: shop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discounts-umbrella
    app.kubernetes.io/version: 1.0.0
  name: discounts-umbrella-offline
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: shop
    app.kubernetes.io/name: discounts-umbrella
  type: ClusterIP
