apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: shop
    app.kubernetes.io/managed-by: kustomzie
    app.kubernetes.io/name: discounts-umbrella
    app.kubernetes.io/version: 1.0.0
  name: discounts-umbrella-offline-prometheus-monitor
spec:
  endpoints:
    - interval: 30s
      path: /q/metrics
      scheme: http
      targetPort: 8080
  selector:
    matchLabels:
      app.kubernetes.io/instance: shop
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: discounts-umbrella
      app.kubernetes.io/version: 1.0.0
