apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  labels:
    app: products
    app.kubernetes.io/instance: shop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: products-umbrella
    app.kubernetes.io/version: 1.0.0
  name: products-analysis-template
spec:
  metrics:
    - name: products-webmetric
      provider:
        web:
          jsonPath: "{$.status}"
          url: >-
            http://products-umbrella-online.gitops-blue-green.svc.cluster.local:8080/q/health/ready
      successCondition: result == 'UP'
