apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-prom-app
  annotations:
    prometheus.io/scrape: "true"
  name: keda-prom-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    type: keda-testing
