apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: keda-testing-sm
  namespace: keda-demo
spec:
  endpoints:
    - scheme: http
      port: http
  namespaceSelector: {}
  selector:
    matchLabels:
      app: keda-prom-app
