apiVersion: v1
data:
  application.colour: none
  application.version: v1.0.1
  quarkus.jaeger.endpoint: "http://jaeger-collector.gitops.svc:14268/api/traces"
  quarkus.jaeger.propagation: b3
  quarkus.jaeger.reporter-log-spans: "true"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.sampler-type: const
  quarkus.jaeger.service-name: discounts
  quarkus.log.level: DEBUG
kind: ConfigMap
metadata:
  labels:
    app: discounts
    app.kubernetes.io/instance: shop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discounts-umbrella
    app.kubernetes.io/version: 1.0.0
  name: discounts-configmap-env-base
