apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-canary

resources:
  - discounts-cm-env-base.yaml
  - discounts-cm-env.yaml
  - products-cm-env-base.yaml
  - products-cm-env.yaml
  - discounts-umbrella-online-service.yaml
  - discounts-umbrella-online-sm.yaml
  - products-umbrella-online-service.yaml
  - products-umbrella-online-sm.yaml
  - discounts-analysistemplate.yaml
  - products-analysistemplate.yaml
  - discounts-rollout.yaml
  - products-rollout.yaml
