apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-gatekeeper
  namespace: open-cluster-management
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper-operator-product-sub
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: gatekeeper-operator-product
              namespace: openshift-operators
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: gatekeeper-operator-product
              source: redhat-operators
              sourceNamespace: openshift-marketplace
        remediationAction: inform
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper-operator-status
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: ClusterServiceVersion
            metadata:
              namespace: openshift-gatekeeper-system
            spec:
              displayName: Gatekeeper Operator
            status:
              phase: Succeeded
        remediationAction: inform
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.gatekeeper.sh/v1alpha1
            kind: Gatekeeper
            metadata:
              name: gatekeeper
            spec:
              audit:
                logLevel: INFO
                replicas: 1
              mutatingWebhook: Disabled
              validatingWebhook: Enabled
              webhook:
                emitAdmissionEvents: Enabled
                logLevel: INFO
                replicas: 2
        remediationAction: inform
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper-status
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                control-plane: audit-controller
              namespace: openshift-gatekeeper-system
            status:
              phase: Running
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                control-plane: controller-manager
              namespace: openshift-gatekeeper-system
            status:
              phase: Running
        remediationAction: inform
        severity: high
  remediationAction: enforce