apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: tracing-system
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317 
    exporters:
      otlp:
        endpoint: tempo-sample-distributor:4317 
        tls:
          insecure: true
    service: 
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
