apiVersion: v1
kind: Namespace
metadata:
  name: tracing-system
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tempo
  namespace: tracing-system
stringData:
  endpoint: http://minio-svc.minio-dev.svc:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: openshift4!
type: Opaque
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: sample
  namespace: tracing-system
spec:
  storageSize: 1Gi
  storage:
    secret:
      name: minio-tempo
      type: s3
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
