apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: remote-ocp
  labels:
    name: remote-ocp
    cloud: auto-detect
    vendor: auto-detect
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: remote-ocp
stringData:
  autoImportRetry: "2"
  token: "REMOTE_API_SERVER_Token"
  server: https://remote-cluster:6443
type: Opaque
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: remote-ocp
  namespace: remote-ocp
spec:
  clusterName: remote-ocp
  clusterNamespace: remote-ocp
  clusterLabels:
    name: remote-ocp
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
    argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
