apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: etcd-encryption
  namespace: open-cluster-management
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: enable-etcd-encryption
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: APIServer
            metadata:
              name: cluster
            spec:
              encryption:
                type: aescbc
        remediationAction: inform
        severity: low
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: enable-etcd-encryption-status-kubeapi
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.openshift.io/v1
            kind: OpenShiftAPIServer
            metadata:
              name: cluster
            status:
              conditions:
              - message: 'All resources encrypted: routes.route.openshift.io'
                reason: EncryptionCompleted
        remediationAction: inform
        severity: low
  remediationAction: inform