apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed
  namespace: default
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
