apiVersion: v1
kind: Pod
metadata:
  name: nginx-allowed
  namespace: default
spec:
  containers:
    - name: nginx
      image: quay.io/rhtw/nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
