{{- $fullName := include "myapp.fullname" . -}}
{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  host: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
{{- end }}