apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-projects
spec:
  generators:
    - git:
        repoURL: https://github.com/CCChou/OpenShift-PoC-Scenario.git
        revision: HEAD
        directories:
          - path: /applicationset/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/CCChou/OpenShift-PoC-Scenario.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-gitops
