apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-canary

resources:
  - ../../base

patches:
  - path: products-rollout.yaml
    target:
      kind: Rollout
      labelSelector: app=products
  - path: products-cm-env-base.yaml
    target:
      kind: ConfigMap
      labelSelector: app=products
