apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-test
  labels:
    app: hpa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-test
  template:
    metadata:
      labels:
        app: hpa-test
    spec:
      containers:
        - name: hpa-test
          image: quay.io/rhtw/sysbench:v1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do sleep 30s; done"
