apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: lokistack-full-policy
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: minio-dev-ns
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: minio-dev
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: minio-dev-ns
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: minio-dev
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: minio
                  namespace: minio-dev
                spec:
                  selector:
                    matchLabels:
                      app: minio
                  replicas: 1
                  template:
                    metadata:
                      labels:
                        app: minio
                    spec:
                      containers:
                        - name: minio
                          image: quay.io/minio/minio:latest
                          command:
                            - /bin/bash
                            - -c
                          args:
                            - minio server /data --console-address :9090
                          volumeMounts:
                            - mountPath: /data
                              name: minio-volume # Corresponds to the `spec.volumes` Persistent Volume
                      volumes:
                        - name: minio-volume
                          persistentVolumeClaim:
                            claimName: minio-volume
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: minio-volume
                  namespace: minio-dev
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Service
                metadata:
                  name: minio-svc
                  namespace: minio-dev
                spec:
                  selector:
                    app: minio
                  ports:
                    - name: 9090-tcp
                      protocol: TCP
                      port: 9090
                      targetPort: 9090
                    - name: 9000-tcp
                      protocol: TCP
                      port: 9000
                      targetPort: 9000
            - complianceType: musthave
              objectDefinition:
                kind: Route
                apiVersion: route.openshift.io/v1
                metadata:
                  name: minio
                  namespace: minio-dev
                  labels:
                    app: minio
                spec:
                  to:
                    kind: Service
                    name: minio-svc
                  port:
                    targetPort: 9090
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-operators-redhat-ns
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators-redhat
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: openshift-operators-redhat-ns
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-operators-redhat-operatorgroup
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-operators-redhat
                  namespace: openshift-operators-redhat
                spec:
                  upgradeStrategy: Default
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: openshift-operators-redhat-operatorgroup
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: loki-operator
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: loki-operator
                  namespace: openshift-operators-redhat
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: loki-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: minio-secret
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  namespace: openshift-logging
                  name: logging-loki-s3
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-logging-ns
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-logging
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: openshift-logging-ns
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-logging-operatorgroup
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-logging
                  namespace: openshift-logging
                spec:
                  targetNamespaces:
                    - openshift-logging
                  upgradeStrategy: Default
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: openshift-logging-operatorgroup
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-operator
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cluster-logging
                  namespace: openshift-logging
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: cluster-logging
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: loki-operator
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: minio-secret
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: logging-operator
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: lokistack
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: loki.grafana.com/v1
                kind: LokiStack
                metadata:
                  name: logging-loki
                  namespace: openshift-logging
                spec:
                  size: 1x.small
                  storage:
                    schemas:
                      - version: v12
                        effectiveDate: "2022-06-01"
                    secret:
                      name: logging-loki-s3
                      type: s3
                  storageClassName: ocs-external-storagecluster-ceph-rbd
                  tenants:
                    mode: openshift-logging
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: lokistack
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: logging-operator
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: clusterlogging
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: logging.openshift.io/v1
                kind: ClusterLogging
                metadata:
                  name: instance
                  namespace: openshift-logging
                spec:
                  managementState: Managed
                  logStore:
                    type: lokistack
                    lokistack:
                      name: logging-loki
                  collection:
                    type: vector
