apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: loki
  access_key_secret: openshift4!
  bucketnames: loki
  endpoint: http://minio-svc.minio-dev.svc:9000
  region: us-east-1
