apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: k8s.gcr.io/ubuntu-slim:0.1
      command: ["/bin/sh"]
      args:
      - "-c"
      - "while true; do timeout 0.5s yes > /dev/null; sleep 0.5s; done"
      volumeMounts:
        - mountPath: /nfs-test
          name: volume-pvc
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: nfs-test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi