apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: spring-petclinic
          resources:
            limits:
              cpu: 4000m
