apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caj-fare
  namespace: openshift-gitops
spec:
  destination:
    namespace: caj-fare
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops
    repoURL: https://github.com/CCChou/caj-fare-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
