apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-tag
  annotations:
    description: |
      Generate a new unique image tag based on format YYYY-MM-YY-HH-MM-SS.
spec:
  results:
  - name: image-tag
    description: The current date in human readable format
  steps:
  - name: generate-image-tag
    image: registry.access.redhat.com/ubi8/ubi-minimal:8.5
    script: |
      #!/usr/bin/env bash
      printf `date +"%Y-%m-%d-%H-%M-%S"` | tee $(results.image-tag.path)