DISTRIBUTED_STORAGE_CONFIG: 
  default: 
    - RadosGWStorage 
    - access_key: quay
      secret_key: openshift4!
      bucket_name: quay
      hostname: minio-svc.minio-dev.svc
      is_secure: false
      port: 9000
      storage_path: /
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: [] 
DISTRIBUTED_STORAGE_PREFERENCE: 
    - default