apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-dev
spec:
  destination:
    name: ""
    namespace: demo-gitops-dev
    server: "https://kubernetes.default.svc"
  source:
    path: 02_Deploy/02_argocd_gitops_deploy/app/overlays/dev
    repoURL: "https://github.com/CCChou/OpenShift-PoC-Scenario.git"
    targetRevision: HEAD
  sources: []
  project: default
