apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
spec:
  destination:
    name: ""
    namespace: spring-petclinic
    server: "https://kubernetes.default.svc"
  source:
    path: 02_Deploy/02_spring_gitops_deploy/app
    repoURL: "https://github.com/CCChou/OpenShift-PoC-Scenario"
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
